name: Personas  
on: [push]
jobs:
  deploy_source:
    name: Deploy API Using Lambda
    strategy:
      matrix:
        node-version: [12.x]
    runs-on: ubuntu-latest
    steps:
    
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: npm install and build
        run: |
          npm ci
          npm run build --if-present
        env:
          CI: true

      - name: /personas get lambda deploy zip
        uses: postman-open-technologies/personas@main
        with:
            args: zip -qq -r m-s-personas-g.zip personas/get/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-personas-g
            zip_file: m-s-personas-g.zip
      - name: /personas post lambda deploy zip
        uses: postman-open-technologies/personas@main
        with:
            args: zip -qq -r m-s-personas-po.zip personas/post/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-personas-po
            zip_file: m-s-personas-po.zip
      - name: /personas/{persona_id} get lambda deploy zip
        uses: postman-open-technologies/personas@main
        with:
            args: zip -qq -r m-s-personas-personas-g.zip personas/persona_id/get/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-personas-personas-g
            zip_file: m-s-personas-personas-g.zip
      - name: /personas/{persona_id} put lambda deploy zip
        uses: postman-open-technologies/personas@main
        with:
            args: zip -qq -r m-s-personas-persona-pu.zip personas/persona_id/put/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-personas-persona-pu
            zip_file: m-s-personas-persona-pu.zip
      - name: /personas/{persona_id} delete lambda deploy zip
        uses: postman-open-technologies/personas@main
        with:
            args: zip -qq -r m-s-personas-persona-d.zip personas/persona_id/delete/index.js node_modules
      - name: videos get lambda deploy
        uses: appleboy/lambda-action@master
        with:
            aws_access_key_id: ${{secrets.AWS_ACCESS_KEY_ID}}
            aws_secret_access_key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
            aws_region: us-west-1
            function_name: m-s-personas-persona-d
            zip_file: m-s-personas-persona-d.zip          